import io.github.cdimascio.dotenv.Dotenv

plugins {
    // Apply the java-library plugin to add support for Java Library
    id 'java-library'
}
sourceCompatibility = 1.8
targetCompatibility = 1.8

version = '0.2.0'
group = 'cmwebgame-ext'
def artifactId = project.name

def dotenv = Dotenv.load() // 读取 .env 文件
task loadEnv {
    doFirst {
        dotenv.entries().each { entry ->
            project.ext[entry.key] = entry.value
        }
    }
}
tasks.withType(JavaCompile) {
    dependsOn loadEnv
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    maven { url 'https://maven.aliyun.com/repository/public/' }
    maven { url 'https://maven.aliyun.com/repository/jcenter' }
    maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
    mavenCentral()
    mavenLocal()
}

configurations {
    /*
    自定义Configuration名称，可通过dependencies()方法向myDependency中加入实际的依赖项
    */
    proviedlib
    compile {
        extendsFrom proviedlib  //compile继承proviedlib
    }
}

ext.versions = [
        jackson   : '1.9.13',
        logback   : '1.0.13',
        slf4j     : '1.7.7',
        httpclient: '4.3.1'
]
dependencies {

    compileOnly(
            "javax.servlet:servlet-api:2.5",
            "net.sf.ehcache:ehcache-core:2.5.2",
            "org.slf4j:slf4j-api:${versions.slf4j}",
            "org.slf4j:slf4j-jdk14:${versions.slf4j}",
            "jgroups:jgroups:2.10.0.Beta2",
            "backport-util-concurrent:backport-util-concurrent:3.1"
    )

    implementation fileTree('libs')

    api(
            "com.github.iwilsonlee:beauty-dao:0.2.0",
            "com.github.iwilsonlee:beauty-core:0.2.0"
    )

    testImplementation('junit:junit:4.12', "com.github.iwilsonlee:beauty-dao:0.2.0")
}

// eclipse{
//     project {
//       buildCommand 'org.eclipse.jdt.core.javabuilder'
//       natures 'org.springsource.ide.eclipse.gradle.core.nature','org.eclipse.jdt.core.javanature'
//     }
//     classpath{
//       //defaultOutputDir = file('build/classes')
//       noExportConfigurations += [configurations.proviedlib]
//       containers 'org.eclipse.jdt.launching.JRE_CONTAINER', 'org.springsource.ide.eclipse.gradle.classpathcontainer'
//     }
// }

def aliMavenUsername = dotenv.get("ALI_MAVEN_USERNAME")
def aliMavenPassword = dotenv.get("ALI_MAVEN_PASSWORD")

apply plugin: 'maven'
uploadArchives {
    repositories {
        mavenLocal()
        mavenDeployer {
            repository(url: 'https://packages.aliyun.com/5ef8675887f8da7d5e937585/maven/repo-yyxnv') {
                authentication(
                        userName: "$aliMavenUsername",
                        password: "$aliMavenPassword"
                )
            }
            pom.version = "$project.version"
            pom.artifactId = "$artifactId"
            pom.groupId = "$project.group"
        }
    }
}

allprojects {
    repositories {
        mavenLocal()
        flatDir {
            dirs 'libs'
        }
        maven {
            url "https://mvn.cloud.alipay.com/nexus/content/repositories/open/"
        }
        maven { url 'http://maven.aliyun.com/nexus/content/groups/public/' }
        maven { url 'http://maven.aliyun.com/nexus/content/repositories/google' }
        maven {
            credentials {
                username "$aliMavenUsername"
                password "$aliMavenPassword"
            }
            url 'https://packages.aliyun.com/5ef8675887f8da7d5e937585/maven/repo-yyxnv'
        }
    }
}
